name: swiftui_flutter
description: SwiftUI &#x2F; Flutter Comparison https://developer.apple.com/tutorials/swiftui/creating-and-combining-views
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  google_maps_flutter:
  mono_kit:
  provider:
  route_observer_mixin:
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - assets/