name: swiftui_flutter
description: SwiftUI &#x2F; Flutter Comparison https://developer.apple.com/tutorials/swiftui/creating-and-combining-views
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  adaptive_dialog: ^1.9.0-0
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  google_maps_flutter:
  mono_kit:
  provider:
  riverpod_annotation:
  route_observer_mixin:
dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
  riverpod_generator:
  riverpod_lint:
flutter:
  uses-material-design: true
  assets:
    - assets/
